### ISSUE TITLE
Data folder structure

### ISSUE THREAD

**Issue by MatrixHuu** [hwang1996/Meta-Concepts-for-Video-Captioning#1]
Dear Hao Wang,
Thanks for your wonderful job, and I want to get the datasets you used in this project to re-implement your job.
I follow the Readme File and download the MSR-VTT datasets you provided and then some problems happened.
Could you mind tell me the final data folder structure this project needed?  
Better appreciate it if you upload the links to all the project data.
Best wish!

**Comment by hwang1996** [comment]
Hi @MatrixHuu,

You may let me know the exact problems you met. Sorry I am not able to upload all the project data, as I do not own the orginal data, and my processed data size is too large (~60 GB).

Attached with the data structure for your reference, maybe some files are useless, which are listed for debug purpose.
[tree.txt](https://github.com/hwang1996/Meta-Concepts-for-Video-Captioning/files/10421847/tree.txt)

Best,
Hao

**Comment by MatrixHuu** [comment]
Thanks for your very helpful reply!  ：）
It helps me a lot.
